name: users_management
description: A crud in Flutter.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  card_settings: ^3.5.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  path_provider: ^2.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  shared_preferences: ^2.0.8
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true